"""add vpn users and sessions

Revision ID: 2dc8d85ddce7
Revises: 9210f2711f2e
Create Date: 2026-07-22 02:07:20.584418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc8d85ddce7'
down_revision: Union[str, Sequence[str], None] = '9210f2711f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vpn_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('ad_sam', sa.String(length=64), nullable=True),
    sa.Column('public_key', sa.String(length=64), nullable=False),
    sa.Column('internal_ip', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vpn_users_tenant_id'), 'vpn_users', ['tenant_id'], unique=False)
    op.create_table('vpn_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vpn_user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint_publico', sa.String(length=64), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_handshake', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bytes_rx', sa.Integer(), nullable=False),
    sa.Column('bytes_tx', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vpn_user_id'], ['vpn_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vpn_sessions')
    op.drop_index(op.f('ix_vpn_users_tenant_id'), table_name='vpn_users')
    op.drop_table('vpn_users')
    # ### end Alembic commands ###
