"""add_sectors_and_hierarchy

Revision ID: 386119c921cd
Revises: 55eab73e75ef
Create Date: 2026-07-08 20:27:12.173729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '386119c921cd'
down_revision: Union[str, Sequence[str], None] = '55eab73e75ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('oee_target', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_sectors_tenant_code')
    )
    op.create_index('ix_sectors_tenant', 'sectors', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sectors_tenant_id'), 'sectors', ['tenant_id'], unique=False)
    op.add_column('assets', sa.Column('sector_id', sa.UUID(), nullable=True))
    hierarchy_level_enum = postgresql.ENUM('Area', 'Line', 'Equipment', name='hierarchy_level')
    hierarchy_level_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('assets', sa.Column('hierarchy_level', postgresql.ENUM('Area', 'Line', 'Equipment', name='hierarchy_level', create_type=False), nullable=True))
    op.create_index(op.f('ix_assets_sector_id'), 'assets', ['sector_id'], unique=False)
    op.create_foreign_key(None, 'assets', 'sectors', ['sector_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_index(op.f('ix_assets_sector_id'), table_name='assets')
    op.drop_column('assets', 'hierarchy_level')
    op.drop_column('assets', 'sector_id')
    op.drop_index(op.f('ix_sectors_tenant_id'), table_name='sectors')
    op.drop_index('ix_sectors_tenant', table_name='sectors')
    op.drop_table('sectors')
    postgresql.ENUM(name='hierarchy_level').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
