"""add integration_settings table

Revision ID: 4bbd256c9b7a
Revises: e5da5dce7ac2
Create Date: 2026-07-11 05:25:16.421810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bbd256c9b7a'
down_revision: Union[str, Sequence[str], None] = 'e5da5dce7ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('peppermint_url', sa.String(length=256), nullable=True),
    sa.Column('peppermint_email', sa.String(length=256), nullable=True),
    sa.Column('peppermint_password', sa.String(length=256), nullable=True),
    sa.Column('peppermint_default_email', sa.String(length=256), nullable=True),
    sa.Column('peppermint_enabled', sa.Boolean(), nullable=False),
    sa.Column('vikunja_url', sa.String(length=256), nullable=True),
    sa.Column('vikunja_token', sa.String(length=512), nullable=True),
    sa.Column('vikunja_project_id', sa.Integer(), nullable=True),
    sa.Column('vikunja_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_ticket_min_severity', sa.String(length=16), nullable=False),
    sa.Column('auto_task_min_severity', sa.String(length=16), nullable=False),
    sa.Column('storm_window_seconds', sa.Integer(), nullable=False),
    sa.Column('storm_threshold', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_settings_tenant_id'), 'integration_settings', ['tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_settings_tenant_id'), table_name='integration_settings')
    op.drop_table('integration_settings')
    # ### end Alembic commands ###
