"""add assets cmdb

Revision ID: 55eab73e75ef
Revises: b28b4f3397d0
Create Date: 2026-07-07 20:48:42.861385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55eab73e75ef'
down_revision: Union[str, Sequence[str], None] = 'b28b4f3397d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('Server', 'Workstation', 'Laptop', 'NetworkSwitch', 'Router', 'Firewall', 'AccessPoint', 'Printer', 'UPS', 'Generator', 'ACUnit', 'PLC', 'HMI', 'SCADA', 'Sensor', 'Scale', 'Camera', 'NVR', 'Phone', 'StorageArray', 'TapeLibrary', 'Other', name='asset_type'), nullable=False),
    sa.Column('layer', sa.Enum('TI', 'OT', 'Physical', name='asset_layer'), nullable=False),
    sa.Column('site', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Maintenance', 'Retired', 'Storage', 'Faulty', name='asset_status'), nullable=False),
    sa.Column('criticality', sa.Enum('Low', 'Medium', 'High', 'Critical', name='asset_criticality'), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('hostname', sa.String(length=128), nullable=True),
    sa.Column('owner_email', sa.String(length=256), nullable=True),
    sa.Column('owner_team', sa.String(length=128), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_assets_tenant_name')
    )
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    op.create_index('ix_assets_tenant_layer', 'assets', ['tenant_id', 'layer'], unique=False)
    op.create_index('ix_assets_tenant_site', 'assets', ['tenant_id', 'site'], unique=False)
    op.create_index('ix_assets_tenant_status', 'assets', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_assets_tenant_type', 'assets', ['tenant_id', 'type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assets_tenant_type', table_name='assets')
    op.drop_index('ix_assets_tenant_status', table_name='assets')
    op.drop_index('ix_assets_tenant_site', table_name='assets')
    op.drop_index('ix_assets_tenant_layer', table_name='assets')
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.drop_table('assets')
    # dropa os enums manualmente (autogenerate nao faz)
    sa.Enum(name='asset_criticality').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='asset_status').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='asset_layer').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='asset_type').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
