"""add wiki pages and versions

Revision ID: 79806b16eb61
Revises: a1b2c3d4e5f6
Create Date: 2026-07-20 23:49:53.041181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79806b16eb61'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wiki_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('author_email', sa.String(length=256), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_wiki_pages_tenant_slug')
    )
    op.create_index(op.f('ix_wiki_pages_slug'), 'wiki_pages', ['slug'], unique=False)
    op.create_index('ix_wiki_pages_tenant_category', 'wiki_pages', ['tenant_id', 'category'], unique=False)
    op.create_index(op.f('ix_wiki_pages_tenant_id'), 'wiki_pages', ['tenant_id'], unique=False)
    op.create_table('wiki_page_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('author_email', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['wiki_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wiki_page_versions_page', 'wiki_page_versions', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wiki_page_versions_page', table_name='wiki_page_versions')
    op.drop_table('wiki_page_versions')
    op.drop_index(op.f('ix_wiki_pages_tenant_id'), table_name='wiki_pages')
    op.drop_index('ix_wiki_pages_tenant_category', table_name='wiki_pages')
    op.drop_index(op.f('ix_wiki_pages_slug'), table_name='wiki_pages')
    op.drop_table('wiki_pages')
    # ### end Alembic commands ###
