"""add backup jobs and restore points

Revision ID: 88cbb17319a6
Revises: 79806b16eb61
Create Date: 2026-07-21 22:55:04.495626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88cbb17319a6'
down_revision: Union[str, Sequence[str], None] = '79806b16eb61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('schedule', sa.String(length=64), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('rpo_target_hours', sa.Integer(), nullable=False),
    sa.Column('rto_target_hours', sa.Integer(), nullable=False),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_jobs_tenant_id'), 'backup_jobs', ['tenant_id'], unique=False)
    op.create_table('restore_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('size_gb', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['backup_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restore_points')
    op.drop_index(op.f('ix_backup_jobs_tenant_id'), table_name='backup_jobs')
    op.drop_table('backup_jobs')
    # ### end Alembic commands ###
