"""add security events

Revision ID: 9210f2711f2e
Revises: 24f30fa75ec8
Create Date: 2026-07-22 01:49:35.751893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9210f2711f2e'
down_revision: Union[str, Sequence[str], None] = '24f30fa75ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_host', sa.String(length=128), nullable=False),
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('rule_description', sa.String(length=256), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('mitre_tactic', sa.String(length=64), nullable=False),
    sa.Column('mitre_technique_id', sa.String(length=16), nullable=False),
    sa.Column('mitre_technique_name', sa.String(length=128), nullable=False),
    sa.Column('raw_summary', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_tenant_id'), 'security_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_security_events_timestamp'), 'security_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_events_timestamp'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_tenant_id'), table_name='security_events')
    op.drop_table('security_events')
    # ### end Alembic commands ###
