"""add network links

Revision ID: 9b2fe569db4e
Revises: 2dc8d85ddce7
Create Date: 2026-07-22 03:34:59.222937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2fe569db4e'
down_revision: Union[str, Sequence[str], None] = '2dc8d85ddce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('asset_a_id', sa.UUID(), nullable=False),
    sa.Column('asset_b_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.Enum('Ethernet', 'Fibra', 'Wireless', name='network_link_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['asset_a_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_b_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_network_links_asset_a', 'network_links', ['asset_a_id'], unique=False)
    op.create_index('ix_network_links_asset_b', 'network_links', ['asset_b_id'], unique=False)
    op.create_index(op.f('ix_network_links_tenant_id'), 'network_links', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_network_links_tenant_id'), table_name='network_links')
    op.drop_index('ix_network_links_asset_b', table_name='network_links')
    op.drop_index('ix_network_links_asset_a', table_name='network_links')
    op.drop_table('network_links')
    # ### end Alembic commands ###
