"""add alerts and status history

Revision ID: b28b4f3397d0
Revises: 7d69e6238979
Create Date: 2026-07-07 19:14:36.354467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b28b4f3397d0'
down_revision: Union[str, Sequence[str], None] = '7d69e6238979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('alertname', sa.String(length=128), nullable=False),
    sa.Column('asset', sa.String(length=128), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('categoria', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('impacto_negocio', sa.Text(), nullable=True),
    sa.Column('generator_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('annotations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'fingerprint', name='uq_alerts_tenant_fingerprint')
    )
    op.create_index(op.f('ix_alerts_alertname'), 'alerts', ['alertname'], unique=False)
    op.create_index(op.f('ix_alerts_asset'), 'alerts', ['asset'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_tenant_id'), 'alerts', ['tenant_id'], unique=False)
    op.create_index('ix_alerts_tenant_starts_at', 'alerts', ['tenant_id', 'starts_at'], unique=False)
    op.create_index('ix_alerts_tenant_status', 'alerts', ['tenant_id', 'status'], unique=False)
    op.create_table('alert_status_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_status_changes_alert_id', 'alert_status_changes', ['alert_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_status_changes_alert_id', table_name='alert_status_changes')
    op.drop_table('alert_status_changes')
    op.drop_index('ix_alerts_tenant_status', table_name='alerts')
    op.drop_index('ix_alerts_tenant_starts_at', table_name='alerts')
    op.drop_index(op.f('ix_alerts_tenant_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_asset'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alertname'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
