"""add_ad_audit_events

Revision ID: b74299c24bd9
Revises: 9355972f4313
Create Date: 2026-07-09 03:43:50.315942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b74299c24bd9'
down_revision: Union[str, Sequence[str], None] = '9355972f4313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_sam', sa.String(length=128), nullable=True),
    sa.Column('actor_sam', sa.String(length=128), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_audit_events_at'), 'ad_audit_events', ['at'], unique=False)
    op.create_index(op.f('ix_ad_audit_events_event_id'), 'ad_audit_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_ad_audit_events_target_sam'), 'ad_audit_events', ['target_sam'], unique=False)
    op.create_index(op.f('ix_ad_audit_events_tenant_id'), 'ad_audit_events', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ad_audit_events_tenant_id'), table_name='ad_audit_events')
    op.drop_index(op.f('ix_ad_audit_events_target_sam'), table_name='ad_audit_events')
    op.drop_index(op.f('ix_ad_audit_events_event_id'), table_name='ad_audit_events')
    op.drop_index(op.f('ix_ad_audit_events_at'), table_name='ad_audit_events')
    op.drop_table('ad_audit_events')
    # ### end Alembic commands ###
