"""add device protocol profiles, commands and executions

Revision ID: cb508ac7501d
Revises: 9b2fe569db4e
Create Date: 2026-07-23 15:45:50.215304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb508ac7501d'
down_revision: Union[str, Sequence[str], None] = '9b2fe569db4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_commands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=False),
    sa.Column('protocol', sa.Enum('SSH', 'WinRM', 'SNMP', 'HTTPAPI', 'Modbus', name='device_protocol'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('Read', 'Action', name='device_command_kind'), nullable=False),
    sa.Column('requires_permission', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_type', 'protocol', 'name', name='uq_device_commands_type_protocol_name')
    )
    op.create_table('device_command_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('command_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('Success', 'Error', 'Simulated', name='device_command_execution_status'), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['command_id'], ['device_commands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_device_command_executions_asset', 'device_command_executions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_device_command_executions_tenant_id'), 'device_command_executions', ['tenant_id'], unique=False)
    op.create_table('device_protocol_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('protocol', sa.Enum('SSH', 'WinRM', 'SNMP', 'HTTPAPI', 'Modbus', name='device_protocol'), nullable=False),
    sa.Column('is_real', sa.Boolean(), nullable=False),
    sa.Column('credential_ref', sa.String(length=128), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'protocol', name='uq_device_protocol_profiles_asset_protocol')
    )
    op.create_index('ix_device_protocol_profiles_asset', 'device_protocol_profiles', ['asset_id'], unique=False)
    op.create_index(op.f('ix_device_protocol_profiles_tenant_id'), 'device_protocol_profiles', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_protocol_profiles_tenant_id'), table_name='device_protocol_profiles')
    op.drop_index('ix_device_protocol_profiles_asset', table_name='device_protocol_profiles')
    op.drop_table('device_protocol_profiles')
    op.drop_index(op.f('ix_device_command_executions_tenant_id'), table_name='device_command_executions')
    op.drop_index('ix_device_command_executions_asset', table_name='device_command_executions')
    op.drop_table('device_command_executions')
    op.drop_table('device_commands')
    # ### end Alembic commands ###
