"""ticket_links

Revision ID: e5da5dce7ac2
Revises: b74299c24bd9
Create Date: 2026-07-10 23:29:01.132111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5da5dce7ac2'
down_revision: Union[str, Sequence[str], None] = 'b74299c24bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('dedup_key', sa.String(length=160), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('peppermint_ticket_id', sa.String(length=64), nullable=True),
    sa.Column('vikunja_task_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_links_dedup_key'), 'ticket_links', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_ticket_links_tenant_id'), 'ticket_links', ['tenant_id'], unique=False)
    op.create_index('ix_ticketlink_dedup_open', 'ticket_links', ['tenant_id', 'dedup_key', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticketlink_dedup_open', table_name='ticket_links')
    op.drop_index(op.f('ix_ticket_links_tenant_id'), table_name='ticket_links')
    op.drop_index(op.f('ix_ticket_links_dedup_key'), table_name='ticket_links')
    op.drop_table('ticket_links')
    # ### end Alembic commands ###
